export default async function emailGeneratorHandler(nodeConfig, inputs, context) {
  const startTime = Date.now();
  try {
    console.log(`[emailGenerator] Executing node ${nodeConfig.id}`);
    await new Promise(resolve => setTimeout(resolve, 350));

    const executionTime = Date.now() - startTime;
    return {
      success: true,
      output: { emailBody: 'Hello, this is an email body generated by Email Generator' },
      logs: {
        nodeId: nodeConfig.id,
        type: 'emailGenerator',
        status: 'completed',
        executionTime: `${executionTime}ms`,
        timestamp: new Date().toISOString(),
      }
    };
  } catch (error) {
    return {
      success: false,
      output: null,
      logs: {
        nodeId: nodeConfig.id,
        type: 'emailGenerator',
        status: 'failed',
        error: error.message,
        timestamp: new Date().toISOString()
      }
    };
  }
}